import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import SideNav from "@/components/navbar/SideNav";
import MarginWidthWrapper from "@/components/navbar/MarginWidthWrapper";
import HeaderMobile from "@/components/navbar/HeaderMobile";
import ReduxProvider from "@/redux/Provider";
import SnackbarProvider from "@/components/notistack/SnackbarProvider";

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '700', '800'],
});


export const metadata: Metadata = {
  title: "Salad Maker Application",
  description: "Generated by Nonthicha Sukcharoen",
  icons: {
    icon: "/icons/favicon.ico",
    shortcut: '/icons/favicon-512x512.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-[#f5f5f5] ${poppins.className}`}>
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <MarginWidthWrapper>
              <HeaderMobile />
              <ReduxProvider>
                <SnackbarProvider>
                  {children}
                </SnackbarProvider>
              </ReduxProvider>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}

