import type { Metadata } from "next";
import { Poppins } from 'next/font/google';
import "./globals.css";
import SideNav from "@/components/layout/navbar/side-nav";
import MarginWidthWrapper from "@/components/layout/navbar/margin-wrapper";
import HeaderNav from "@/components/layout/navbar/header-nav";
import PageWrapper from "@/components/layout/navbar/page-wrapper";
import HeaderMobile from "@/components/layout/navbar/header-mobile";

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '700', '800'],
});


export const metadata: Metadata = {
  title: "Salad Maker Application",
  description: "Generated by Nonthicha Sukcharoen",
  icons: {
    icon: "/icons/favicon.ico",
    shortcut: '/icons/favicon-512x512.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-white ${poppins.className}`}>
        <div className="flex">
          <SideNav />
          <main className="flex-1">
            <MarginWidthWrapper>
              <HeaderNav />
              <HeaderMobile />
              <PageWrapper>{children}</PageWrapper>
            </MarginWidthWrapper>
          </main>
        </div>
      </body>
    </html>
  );
}

